# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 678)
        MainWindow.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("color: rgb(1, 255, 1);")
        self.centralwidget.setObjectName("centralwidget")
        self.frameleft = QtWidgets.QFrame(self.centralwidget)
        self.frameleft.setGeometry(QtCore.QRect(10, 40, 131, 571))
        self.frameleft.setStyleSheet("background-color:rgb(0, 0, 0);\n"
" border-top: 2px solid blue; \n"
" border-left: 2px solid blue; \n"
" border-right: 2px solid blue; \n"
" border-bottom: 2px solid blue; ")
        self.frameleft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameleft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameleft.setObjectName("frameleft")
        self.btnDashboard = QtWidgets.QPushButton(self.frameleft)
        self.btnDashboard.setGeometry(QtCore.QRect(15, 100, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btnDashboard.setFont(font)
        self.btnDashboard.setAutoFillBackground(False)
        self.btnDashboard.setStyleSheet("QPushButton {\n"
"color: rgb(88, 1, 200);\n"
"border-radius:0;\n"
"border:0;\n"
"background-color: rgb(0, 0, 0);\n"
"text-align:right;\n"
"qproperty-icon: url(:/newPrefix/icons.png);\n"
"qproperty-iconSize: 20px 20px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(24, 27, 40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:#333;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDashboard.setIcon(icon)
        self.btnDashboard.setIconSize(QtCore.QSize(20, 20))
        self.btnDashboard.setObjectName("btnDashboard")
        self.btnFormular = QtWidgets.QPushButton(self.frameleft)
        self.btnFormular.setGeometry(QtCore.QRect(15, 140, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btnFormular.setFont(font)
        self.btnFormular.setStyleSheet("QPushButton {\n"
"color: rgb(88, 1, 200);\n"
"border-radius:0;\n"
"border:0;\n"
"background-color: rgb(0, 0, 0);\n"
"text-align:right;\n"
"qproperty-icon: url(:/newPrefix/icons.png);\n"
"qproperty-iconSize: 20px 20px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(24, 27, 40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:#333;\n"
"}")
        self.btnFormular.setIcon(icon)
        self.btnFormular.setIconSize(QtCore.QSize(20, 20))
        self.btnFormular.setObjectName("btnFormular")
        self.btnStocks = QtWidgets.QPushButton(self.frameleft)
        self.btnStocks.setGeometry(QtCore.QRect(15, 220, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btnStocks.setFont(font)
        self.btnStocks.setStyleSheet("QPushButton {\n"
"color: rgb(88, 1, 200);\n"
"border-radius:0;\n"
"border:0;\n"
"background-color: rgb(0, 0, 0);\n"
"text-align:right;\n"
"qproperty-icon: url(:/newPrefix/icons.png);\n"
"qproperty-iconSize: 20px 20px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(24, 27, 40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:#333;\n"
"}")
        self.btnStocks.setIcon(icon)
        self.btnStocks.setIconSize(QtCore.QSize(20, 20))
        self.btnStocks.setObjectName("btnStocks")
        self.btnCompanyFormular = QtWidgets.QPushButton(self.frameleft)
        self.btnCompanyFormular.setGeometry(QtCore.QRect(15, 180, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btnCompanyFormular.setFont(font)
        self.btnCompanyFormular.setStyleSheet("QPushButton {\n"
"color: rgb(88, 1, 200);\n"
"border-radius:0;\n"
"border:0;\n"
"background-color: rgb(0, 0, 0);\n"
"text-align:right;\n"
"qproperty-icon: url(:/newPrefix/icons.png);\n"
"qproperty-iconSize: 20px 20px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(24, 27, 40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:#333;\n"
"}")
        self.btnCompanyFormular.setIcon(icon)
        self.btnCompanyFormular.setIconSize(QtCore.QSize(20, 20))
        self.btnCompanyFormular.setObjectName("btnCompanyFormular")
        self.widget_3 = QtWidgets.QWidget(self.frameleft)
        self.widget_3.setGeometry(QtCore.QRect(5, 5, 121, 81))
        self.widget_3.setStyleSheet("QWidget\n"
"{\n"
"  border-image:url(:/newPrefix/logomoney.jpg)0 0 0 0 stretch stretch;\n"
" border-width: 0px;\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; \n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.btnForex = QtWidgets.QPushButton(self.frameleft)
        self.btnForex.setGeometry(QtCore.QRect(13, 260, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btnForex.setFont(font)
        self.btnForex.setStyleSheet("QPushButton {\n"
"color: rgb(88, 1, 200);\n"
"border-radius:0;\n"
"border:0;\n"
"background-color: rgb(0, 0, 0);\n"
"text-align:right;\n"
"qproperty-icon: url(:/newPrefix/icons.png);\n"
"qproperty-iconSize: 20px 20px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(24, 27, 40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:#333;\n"
"}")
        self.btnForex.setIcon(icon)
        self.btnForex.setIconSize(QtCore.QSize(20, 20))
        self.btnForex.setObjectName("btnForex")
        self.btnFutures = QtWidgets.QPushButton(self.frameleft)
        self.btnFutures.setGeometry(QtCore.QRect(15, 300, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btnFutures.setFont(font)
        self.btnFutures.setStyleSheet("QPushButton {\n"
"color: rgb(88, 1, 200);\n"
"border-radius:0;\n"
"border:0;\n"
"background-color: rgb(0, 0, 0);\n"
"text-align:right;\n"
"qproperty-icon: url(:/newPrefix/icons.png);\n"
"qproperty-iconSize: 20px 20px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(24, 27, 40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:#333;\n"
"}")
        self.btnFutures.setIcon(icon)
        self.btnFutures.setIconSize(QtCore.QSize(20, 20))
        self.btnFutures.setObjectName("btnFutures")
        self.btnCrypto = QtWidgets.QPushButton(self.frameleft)
        self.btnCrypto.setGeometry(QtCore.QRect(10, 340, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btnCrypto.setFont(font)
        self.btnCrypto.setStyleSheet("QPushButton {\n"
"color: rgb(88, 1, 200);\n"
"border-radius:0;\n"
"border:0;\n"
"background-color: rgb(0, 0, 0);\n"
"text-align:right;\n"
"qproperty-icon: url(:/newPrefix/icons.png);\n"
"qproperty-iconSize: 20px 20px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(24, 27, 40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:#333;\n"
"}")
        self.btnCrypto.setIcon(icon)
        self.btnCrypto.setIconSize(QtCore.QSize(20, 20))
        self.btnCrypto.setObjectName("btnCrypto")
        self.btnSettings = QtWidgets.QPushButton(self.frameleft)
        self.btnSettings.setGeometry(QtCore.QRect(10, 500, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btnSettings.setFont(font)
        self.btnSettings.setStyleSheet("QPushButton {\n"
"color: rgb(88, 1, 200);\n"
"border-radius:0;\n"
"border:0;\n"
"background-color: rgb(0, 0, 0);\n"
"text-align:right;\n"
"qproperty-icon: url(:/newPrefix/icons.png);\n"
"qproperty-iconSize: 20px 20px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(24, 27, 40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:#333;\n"
"}")
        self.btnSettings.setIcon(icon)
        self.btnSettings.setIconSize(QtCore.QSize(20, 20))
        self.btnSettings.setObjectName("btnSettings")
        self.btnVersion = QtWidgets.QPushButton(self.frameleft)
        self.btnVersion.setGeometry(QtCore.QRect(11, 540, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btnVersion.setFont(font)
        self.btnVersion.setStyleSheet("QPushButton {\n"
"color: rgb(88, 1, 200);\n"
"border-radius:0;\n"
"border:0;\n"
"background-color: rgb(0, 0, 0);\n"
"text-align:right;\n"
"qproperty-icon: url(:/newPrefix/icons.png);\n"
"qproperty-iconSize: 20px 20px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(24, 27, 40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:#333;\n"
"}")
        self.btnVersion.setIcon(icon)
        self.btnVersion.setIconSize(QtCore.QSize(20, 20))
        self.btnVersion.setObjectName("btnVersion")
        self.btnDashboard.raise_()
        self.btnFormular.raise_()
        self.btnCompanyFormular.raise_()
        self.widget_3.raise_()
        self.btnStocks.raise_()
        self.btnForex.raise_()
        self.btnFutures.raise_()
        self.btnCrypto.raise_()
        self.btnSettings.raise_()
        self.btnVersion.raise_()
        self.framdown = QtWidgets.QFrame(self.centralwidget)
        self.framdown.setGeometry(QtCore.QRect(10, 619, 1041, 51))
        self.framdown.setStyleSheet("background-color:rgb(0, 0, 0);\n"
" border-top: 2px solid blue; \n"
" border-left: 2px solid blue; \n"
" border-right: 2px solid blue; \n"
" border-bottom: 2px solid blue; ")
        self.framdown.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framdown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framdown.setObjectName("framdown")
        self.lbldate = QtWidgets.QLabel(self.framdown)
        self.lbldate.setGeometry(QtCore.QRect(945, 30, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbldate.setFont(font)
        self.lbldate.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lbldate.setObjectName("lbldate")
        self.frmDashboard = QtWidgets.QFrame(self.centralwidget)
        self.frmDashboard.setGeometry(QtCore.QRect(150, 110, 901, 501))
        self.frmDashboard.setStyleSheet(" border-top: 2px solid blue; \n"
" border-left: 2px solid blue; \n"
" border-right: 2px solid blue; \n"
" border-bottom: 2px solid blue; \n"
"background-image: url(:/newPrefix/forex.jpeg);")
        self.frmDashboard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmDashboard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmDashboard.setObjectName("frmDashboard")
        self.graphicsView = QtWidgets.QGraphicsView(self.frmDashboard)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 461, 241))
        self.graphicsView.setStyleSheet("background-image: url(:/newPrefix/black.jpg);")
        self.graphicsView.setObjectName("graphicsView")
        self.frameQuickOverview = QtWidgets.QFrame(self.frmDashboard)
        self.frameQuickOverview.setGeometry(QtCore.QRect(30, 70, 131, 131))
        self.frameQuickOverview.setStyleSheet("QFrame{\n"
"    border-radius: 65px;    \n"
" border-top: 2px solid blue; \n"
" border-left: 2px solid blue; \n"
" border-right: 2px solid blue; \n"
" border-bottom: 2px solid blue; \n"
"background-image: url(:/newPrefix/black.jpeg);\n"
"}")
        self.frameQuickOverview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameQuickOverview.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameQuickOverview.setObjectName("frameQuickOverview")
        self.lblQuickOverview = QtWidgets.QLabel(self.frmDashboard)
        self.lblQuickOverview.setGeometry(QtCore.QRect(30, 20, 151, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lblQuickOverview.setFont(font)
        self.lblQuickOverview.setStyleSheet("color: rgb(88, 150, 250);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; \n"
"background-image: url(:/newPrefix/black.jpg);")
        self.lblQuickOverview.setObjectName("lblQuickOverview")
        self.frame_2 = QtWidgets.QFrame(self.frmDashboard)
        self.frame_2.setGeometry(QtCore.QRect(360, 150, 101, 91))
        self.frame_2.setStyleSheet("background-image: url(:/newPrefix/black.jpeg);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; \n"
"")
        self.label_2.setObjectName("label_2")
        self.btnCurrency_3 = QtWidgets.QPushButton(self.frame_2)
        self.btnCurrency_3.setGeometry(QtCore.QRect(80, 50, 14, 14))
        self.btnCurrency_3.setMinimumSize(QtCore.QSize(14, 14))
        self.btnCurrency_3.setMaximumSize(QtCore.QSize(17, 17))
        self.btnCurrency_3.setToolTip("")
        self.btnCurrency_3.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 6px;        \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {        \n"
"        background-color: rgb(0, 200, 255);\n"
"}")
        self.btnCurrency_3.setText("")
        self.btnCurrency_3.setIconSize(QtCore.QSize(14, 14))
        self.btnCurrency_3.setObjectName("btnCurrency_3")
        self.btnCurrency_2 = QtWidgets.QPushButton(self.frame_2)
        self.btnCurrency_2.setGeometry(QtCore.QRect(80, 70, 14, 14))
        self.btnCurrency_2.setMinimumSize(QtCore.QSize(14, 14))
        self.btnCurrency_2.setMaximumSize(QtCore.QSize(17, 17))
        self.btnCurrency_2.setToolTip("")
        self.btnCurrency_2.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 6px;        \n"
"    background-color: rgb(150, 10, 250)\n"
"}\n"
"QPushButton:hover {        \n"
"        background-color: rgb(0, 200, 255);\n"
"}")
        self.btnCurrency_2.setText("")
        self.btnCurrency_2.setIconSize(QtCore.QSize(14, 14))
        self.btnCurrency_2.setObjectName("btnCurrency_2")
        self.btnCurrency_5 = QtWidgets.QPushButton(self.frame_2)
        self.btnCurrency_5.setGeometry(QtCore.QRect(80, 10, 14, 14))
        self.btnCurrency_5.setMinimumSize(QtCore.QSize(14, 14))
        self.btnCurrency_5.setMaximumSize(QtCore.QSize(17, 17))
        self.btnCurrency_5.setToolTip("")
        self.btnCurrency_5.setAutoFillBackground(False)
        self.btnCurrency_5.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 6px;        \n"
"    background-color: rgb(0,255 , 0);\n"
"background-image: url(:/newPrefix/green.jpeg);\n"
"}\n"
"QPushButton:hover {        \n"
"        background-color: rgb(0, 200, 255);\n"
"}")
        self.btnCurrency_5.setText("")
        self.btnCurrency_5.setIconSize(QtCore.QSize(14, 14))
        self.btnCurrency_5.setObjectName("btnCurrency_5")
        self.btnCurrency_4 = QtWidgets.QPushButton(self.frame_2)
        self.btnCurrency_4.setGeometry(QtCore.QRect(80, 30, 14, 14))
        self.btnCurrency_4.setMinimumSize(QtCore.QSize(14, 14))
        self.btnCurrency_4.setMaximumSize(QtCore.QSize(17, 17))
        self.btnCurrency_4.setToolTip("")
        self.btnCurrency_4.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 6px;        \n"
"    background-color: rgb(0, 0, 255);\n"
"}\n"
"QPushButton:hover {        \n"
"        background-color: rgb(0, 200, 255);\n"
"}")
        self.btnCurrency_4.setText("")
        self.btnCurrency_4.setIconSize(QtCore.QSize(14, 14))
        self.btnCurrency_4.setObjectName("btnCurrency_4")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; \n"
"")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; \n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; \n"
"")
        self.label_7.setObjectName("label_7")
        self.label_2.raise_()
        self.btnCurrency_3.raise_()
        self.btnCurrency_2.raise_()
        self.btnCurrency_4.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.btnCurrency_5.raise_()
        self.frame_3 = QtWidgets.QFrame(self.frmDashboard)
        self.frame_3.setGeometry(QtCore.QRect(480, 10, 411, 241))
        self.frame_3.setStyleSheet("background-image: url(:/newPrefix/black.jpg);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lblQuickOverview_2 = QtWidgets.QLabel(self.frame_3)
        self.lblQuickOverview_2.setGeometry(QtCore.QRect(10, 10, 151, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lblQuickOverview_2.setFont(font)
        self.lblQuickOverview_2.setStyleSheet("color: rgb(88, 150, 250);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; \n"
"background-image: url(:/newPrefix/black.jpg);")
        self.lblQuickOverview_2.setObjectName("lblQuickOverview_2")
        self.frame_4 = QtWidgets.QFrame(self.frmDashboard)
        self.frame_4.setGeometry(QtCore.QRect(10, 260, 461, 231))
        self.frame_4.setStyleSheet("background-image: url(:/newPrefix/black.jpg);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.lblQuickOverview_3 = QtWidgets.QLabel(self.frame_4)
        self.lblQuickOverview_3.setGeometry(QtCore.QRect(10, 10, 151, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lblQuickOverview_3.setFont(font)
        self.lblQuickOverview_3.setStyleSheet("color: rgb(88, 150, 250);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; \n"
"background-image: url(:/newPrefix/black.jpg);")
        self.lblQuickOverview_3.setObjectName("lblQuickOverview_3")
        self.frame_5 = QtWidgets.QFrame(self.frmDashboard)
        self.frame_5.setGeometry(QtCore.QRect(480, 260, 411, 231))
        self.frame_5.setStyleSheet("background-image: url(:/newPrefix/black.jpg);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.lblQuickOverview_4 = QtWidgets.QLabel(self.frame_5)
        self.lblQuickOverview_4.setGeometry(QtCore.QRect(10, 10, 151, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lblQuickOverview_4.setFont(font)
        self.lblQuickOverview_4.setStyleSheet("color: rgb(88, 150, 250);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; \n"
"background-image: url(:/newPrefix/black.jpg);")
        self.lblQuickOverview_4.setObjectName("lblQuickOverview_4")
        self.frame_3.raise_()
        self.graphicsView.raise_()
        self.frameQuickOverview.raise_()
        self.lblQuickOverview.raise_()
        self.frame_2.raise_()
        self.frame_4.raise_()
        self.frame_5.raise_()
        self.frmCompanyFormular = QtWidgets.QFrame(self.centralwidget)
        self.frmCompanyFormular.setGeometry(QtCore.QRect(150, 110, 901, 501))
        self.frmCompanyFormular.setStyleSheet("background-color:rgb(0,0, 0);\n"
" border-top: 2px solid blue; \n"
" border-left: 2px solid blue; \n"
" border-right: 2px solid blue; \n"
" border-bottom: 2px solid blue; ")
        self.frmCompanyFormular.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmCompanyFormular.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmCompanyFormular.setObjectName("frmCompanyFormular")
        self.label_3 = QtWidgets.QLabel(self.frmCompanyFormular)
        self.label_3.setGeometry(QtCore.QRect(650, 580, 101, 31))
        self.label_3.setObjectName("label_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.frmCompanyFormular)
        self.comboBox_3.setGeometry(QtCore.QRect(10, 10, 171, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("background-color: rgb(10,10,10);\n"
"color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.label_5 = QtWidgets.QLabel(self.frmCompanyFormular)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 121, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.frmCompanyFormular)
        self.lineEdit.setGeometry(QtCore.QRect(130, 70, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border: 2px solid rgb(37,39,48);\n"
"border-radius: 10px;\n"
"color: #FFF;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"background-color: rgb(34,36,44);\n"
"color:rgb(0,0,255);\n"
"}\n"
"QLineEdit:hover { border: 2px solid rgb(48,50,62);}QLineEdit:focus{border:2px solid rgb(48,50,60)n}")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.btnSend = QtWidgets.QPushButton(self.frmCompanyFormular)
        self.btnSend.setGeometry(QtCore.QRect(800, 470, 91, 21))
        self.btnSend.setStyleSheet("QPushButton{\n"
"border: 2px solid rgb(37,39,48);\n"
"border-radius: 10px;\n"
"color: #FFF;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"background-color: rgb(34,36,44);\n"
"color:rgb(0,0,255);\n"
"}")
        self.btnSend.setObjectName("btnSend")
        self.btn_maximize = QtWidgets.QPushButton(self.centralwidget)
        self.btn_maximize.setGeometry(QtCore.QRect(985, 10, 13, 13))
        self.btn_maximize.setMinimumSize(QtCore.QSize(13, 13))
        self.btn_maximize.setMaximumSize(QtCore.QSize(13, 13))
        self.btn_maximize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 6px;    \n"
"    background-color: rgb(126, 248, 54);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgba(85, 255, 127, 150);\n"
"}")
        self.btn_maximize.setText("")
        self.btn_maximize.setIconSize(QtCore.QSize(10, 10))
        self.btn_maximize.setObjectName("btn_maximize")
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(1025, 10, 14, 14))
        self.btn_close.setMinimumSize(QtCore.QSize(14, 14))
        self.btn_close.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 6px;        \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {        \n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setIconSize(QtCore.QSize(14, 14))
        self.btn_close.setObjectName("btn_close")
        self.btn_minimize = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minimize.setGeometry(QtCore.QRect(945, 10, 13, 13))
        self.btn_minimize.setMinimumSize(QtCore.QSize(13, 13))
        self.btn_minimize.setMaximumSize(QtCore.QSize(13, 13))
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 6px;        \n"
"    background-color: rgb(243, 213,11 0);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgba(255, 170, 0, 150);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setIconSize(QtCore.QSize(10, 10))
        self.btn_minimize.setObjectName("btn_minimize")
        self.frameup = QtWidgets.QFrame(self.centralwidget)
        self.frameup.setGeometry(QtCore.QRect(0, 0, 1061, 36))
        self.frameup.setStyleSheet("background-color: rgb(24, 27, 40);")
        self.frameup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameup.setObjectName("frameup")
        self.lblcapitalmanager = QtWidgets.QLabel(self.frameup)
        self.lblcapitalmanager.setGeometry(QtCore.QRect(20, -7, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblcapitalmanager.setFont(font)
        self.lblcapitalmanager.setStyleSheet("color: rgb(88, 1, 200);")
        self.lblcapitalmanager.setObjectName("lblcapitalmanager")
        self.frametop = QtWidgets.QFrame(self.centralwidget)
        self.frametop.setGeometry(QtCore.QRect(150, 40, 901, 61))
        self.frametop.setStyleSheet("background-color:rgb(0, 0, 0);\n"
" border-top: 2px solid blue; \n"
" border-left: 2px solid blue; \n"
" border-right: 2px solid blue; \n"
" border-bottom: 2px solid blue; ")
        self.frametop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frametop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frametop.setObjectName("frametop")
        self.lblname = QtWidgets.QLabel(self.frametop)
        self.lblname.setGeometry(QtCore.QRect(710, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblname.setFont(font)
        self.lblname.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblname.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lblname.setTextFormat(QtCore.Qt.AutoText)
        self.lblname.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblname.setObjectName("lblname")
        self.frmFormular = QtWidgets.QFrame(self.centralwidget)
        self.frmFormular.setGeometry(QtCore.QRect(150, 110, 901, 501))
        self.frmFormular.setStyleSheet("background-color:rgb(0,0, 0);\n"
" border-top: 2px solid blue; \n"
" border-left: 2px solid blue; \n"
" border-right: 2px solid blue; \n"
" border-bottom: 2px solid blue; ")
        self.frmFormular.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmFormular.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmFormular.setObjectName("frmFormular")
        self.frame = QtWidgets.QFrame(self.frmFormular)
        self.frame.setGeometry(QtCore.QRect(10, 10, 711, 201))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnSpend = QtWidgets.QPushButton(self.frame)
        self.btnSpend.setGeometry(QtCore.QRect(610, 170, 91, 21))
        self.btnSpend.setStyleSheet("QPushButton{\n"
"border: 2px solid rgb(37,39,48);\n"
"border-radius: 10px;\n"
"color: #FFF;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"background-color: rgb(34,36,44);\n"
"color:rgb(0,0,255);\n"
"}")
        self.btnSpend.setObjectName("btnSpend")
        self.cbspendmoney = QtWidgets.QComboBox(self.frame)
        self.cbspendmoney.setGeometry(QtCore.QRect(10, 60, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.cbspendmoney.setFont(font)
        self.cbspendmoney.setStyleSheet("background-color: rgb(10,10,10);\n"
"color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.cbspendmoney.setEditable(False)
        self.cbspendmoney.setObjectName("cbspendmoney")
        self.cbspendmoney.addItem("")
        self.cbspendmoney.addItem("")
        self.cbspendmoney.addItem("")
        self.cbspendmoney.addItem("")
        self.cbspendmoney.addItem("")
        self.lespend = QtWidgets.QLineEdit(self.frame)
        self.lespend.setGeometry(QtCore.QRect(160, 110, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lespend.setFont(font)
        self.lespend.setStyleSheet("QLineEdit{\n"
"border: 2px solid rgb(37,39,48);\n"
"border-radius: 10px;\n"
"color: #FFF;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"background-color: rgb(34,36,44);\n"
"color:rgb(0,0,255);\n"
"}\n"
"QLineEdit:hover { border: 2px solid rgb(48,50,62);}QLineEdit:focus{border:2px solid rgb(48,50,60)n}")
        self.lespend.setAlignment(QtCore.Qt.AlignCenter)
        self.lespend.setObjectName("lespend")
        self.lblSpendMoney = QtWidgets.QLabel(self.frame)
        self.lblSpendMoney.setGeometry(QtCore.QRect(10, 110, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lblSpendMoney.setFont(font)
        self.lblSpendMoney.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lblSpendMoney.setObjectName("lblSpendMoney")
        self.lblSpendMoney_2 = QtWidgets.QLabel(self.frame)
        self.lblSpendMoney_2.setGeometry(QtCore.QRect(10, 10, 131, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lblSpendMoney_2.setFont(font)
        self.lblSpendMoney_2.setStyleSheet("color: rgb(88, 150, 250);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lblSpendMoney_2.setObjectName("lblSpendMoney_2")
        self.pbSpendMoney = QtWidgets.QProgressBar(self.frame)
        self.pbSpendMoney.setGeometry(QtCore.QRect(160, 140, 421, 20))
        self.pbSpendMoney.setStyleSheet("QProgressBar {\n"
"    \n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));\n"
"}")
        self.pbSpendMoney.setMaximum(100)
        self.pbSpendMoney.setProperty("value", 0)
        self.pbSpendMoney.setObjectName("pbSpendMoney")
        self.pbSpendMoneyEuro = QtWidgets.QProgressBar(self.frame)
        self.pbSpendMoneyEuro.setGeometry(QtCore.QRect(160, 170, 421, 20))
        self.pbSpendMoneyEuro.setStyleSheet("QProgressBar {\n"
"    \n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));\n"
"}")
        self.pbSpendMoneyEuro.setMaximum(100)
        self.pbSpendMoneyEuro.setProperty("value", 0)
        self.pbSpendMoneyEuro.setObjectName("pbSpendMoneyEuro")
        self.frameHistory = QtWidgets.QFrame(self.frmFormular)
        self.frameHistory.setGeometry(QtCore.QRect(730, 10, 161, 481))
        self.frameHistory.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHistory.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHistory.setObjectName("frameHistory")
        self.lblHistory = QtWidgets.QLabel(self.frameHistory)
        self.lblHistory.setGeometry(QtCore.QRect(10, 10, 91, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lblHistory.setFont(font)
        self.lblHistory.setStyleSheet("color: rgb(88, 150, 250);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lblHistory.setObjectName("lblHistory")
        self.listwidgethistory = QtWidgets.QListWidget(self.frameHistory)
        self.listwidgethistory.setGeometry(QtCore.QRect(10, 50, 141, 421))
        self.listwidgethistory.setStyleSheet("color: rgb(255, 0, 0);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.listwidgethistory.setObjectName("listwidgethistory")
        self.listwidgethistory.raise_()
        self.lblHistory.raise_()
        self.frameAccountStatistic = QtWidgets.QFrame(self.frmFormular)
        self.frameAccountStatistic.setGeometry(QtCore.QRect(10, 220, 711, 271))
        self.frameAccountStatistic.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAccountStatistic.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAccountStatistic.setObjectName("frameAccountStatistic")
        self.pbAccount1 = QtWidgets.QProgressBar(self.frameAccountStatistic)
        self.pbAccount1.setGeometry(QtCore.QRect(160, 97, 421, 20))
        self.pbAccount1.setStyleSheet("QProgressBar {\n"
"    \n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));\n"
"}")
        self.pbAccount1.setProperty("value", 0)
        self.pbAccount1.setObjectName("pbAccount1")
        self.lblAccount2 = QtWidgets.QLabel(self.frameAccountStatistic)
        self.lblAccount2.setGeometry(QtCore.QRect(35, 127, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lblAccount2.setFont(font)
        self.lblAccount2.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lblAccount2.setObjectName("lblAccount2")
        self.lblAccount3 = QtWidgets.QLabel(self.frameAccountStatistic)
        self.lblAccount3.setGeometry(QtCore.QRect(35, 157, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lblAccount3.setFont(font)
        self.lblAccount3.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lblAccount3.setObjectName("lblAccount3")
        self.lblAccount1 = QtWidgets.QLabel(self.frameAccountStatistic)
        self.lblAccount1.setGeometry(QtCore.QRect(35, 97, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lblAccount1.setFont(font)
        self.lblAccount1.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lblAccount1.setObjectName("lblAccount1")
        self.pbAccount2 = QtWidgets.QProgressBar(self.frameAccountStatistic)
        self.pbAccount2.setGeometry(QtCore.QRect(160, 127, 421, 20))
        self.pbAccount2.setStyleSheet("QProgressBar {\n"
"    \n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));\n"
"}")
        self.pbAccount2.setProperty("value", 0)
        self.pbAccount2.setObjectName("pbAccount2")
        self.lblTotal = QtWidgets.QLabel(self.frameAccountStatistic)
        self.lblTotal.setGeometry(QtCore.QRect(30, 237, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lblTotal.setFont(font)
        self.lblTotal.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lblTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTotal.setObjectName("lblTotal")
        self.lblMainAccount = QtWidgets.QLabel(self.frameAccountStatistic)
        self.lblMainAccount.setGeometry(QtCore.QRect(20, 62, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lblMainAccount.setFont(font)
        self.lblMainAccount.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lblMainAccount.setObjectName("lblMainAccount")
        self.lblAccount4 = QtWidgets.QLabel(self.frameAccountStatistic)
        self.lblAccount4.setGeometry(QtCore.QRect(35, 187, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lblAccount4.setFont(font)
        self.lblAccount4.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lblAccount4.setObjectName("lblAccount4")
        self.pbAccount4 = QtWidgets.QProgressBar(self.frameAccountStatistic)
        self.pbAccount4.setGeometry(QtCore.QRect(160, 187, 421, 20))
        self.pbAccount4.setStyleSheet("QProgressBar {\n"
"    \n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));\n"
"}")
        self.pbAccount4.setProperty("value", 0)
        self.pbAccount4.setObjectName("pbAccount4")
        self.pbMainAccount = QtWidgets.QProgressBar(self.frameAccountStatistic)
        self.pbMainAccount.setGeometry(QtCore.QRect(160, 67, 421, 20))
        self.pbMainAccount.setStyleSheet("QProgressBar {\n"
"    \n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));\n"
"}")
        self.pbMainAccount.setMaximum(100)
        self.pbMainAccount.setProperty("value", 0)
        self.pbMainAccount.setObjectName("pbMainAccount")
        self.pbTotal = QtWidgets.QProgressBar(self.frameAccountStatistic)
        self.pbTotal.setGeometry(QtCore.QRect(160, 240, 421, 20))
        self.pbTotal.setStyleSheet("QProgressBar {\n"
"    \n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(44, 2, 100, 255));\n"
"}")
        self.pbTotal.setProperty("value", 100)
        self.pbTotal.setObjectName("pbTotal")
        self.pbAccount3 = QtWidgets.QProgressBar(self.frameAccountStatistic)
        self.pbAccount3.setGeometry(QtCore.QRect(160, 157, 421, 20))
        self.pbAccount3.setStyleSheet("QProgressBar {\n"
"    \n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));\n"
"}")
        self.pbAccount3.setProperty("value", 0)
        self.pbAccount3.setObjectName("pbAccount3")
        self.btnSend_2 = QtWidgets.QPushButton(self.frameAccountStatistic)
        self.btnSend_2.setGeometry(QtCore.QRect(610, 240, 91, 21))
        self.btnSend_2.setStyleSheet("QPushButton{\n"
"border: 2px solid rgb(37,39,48);\n"
"border-radius: 10px;\n"
"color: #FFF;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"background-color: rgb(34,36,44);\n"
"color:rgb(0,0,255);\n"
"}")
        self.btnSend_2.setObjectName("btnSend_2")
        self.lblAccountStatistic = QtWidgets.QLabel(self.frameAccountStatistic)
        self.lblAccountStatistic.setGeometry(QtCore.QRect(10, 10, 161, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lblAccountStatistic.setFont(font)
        self.lblAccountStatistic.setStyleSheet("color: rgb(88, 150, 250);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lblAccountStatistic.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblAccountStatistic.setLineWidth(1)
        self.lblAccountStatistic.setObjectName("lblAccountStatistic")
        self.btnCurrency = QtWidgets.QPushButton(self.frameAccountStatistic)
        self.btnCurrency.setGeometry(QtCore.QRect(680, 220, 14, 14))
        self.btnCurrency.setMinimumSize(QtCore.QSize(14, 14))
        self.btnCurrency.setMaximumSize(QtCore.QSize(17, 17))
        self.btnCurrency.setToolTip("")
        self.btnCurrency.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 6px;        \n"
"    background-color: rgb(0, 150, 240);\n"
"}\n"
"QPushButton:hover {        \n"
"        background-color: rgb(0, 200, 255);\n"
"}")
        self.btnCurrency.setText("")
        self.btnCurrency.setIconSize(QtCore.QSize(14, 14))
        self.btnCurrency.setObjectName("btnCurrency")
        self.lblcurrency = QtWidgets.QLabel(self.frameAccountStatistic)
        self.lblcurrency.setGeometry(QtCore.QRect(590, 242, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblcurrency.setFont(font)
        self.lblcurrency.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; \n"
" text-align:right;")
        self.lblcurrency.setObjectName("lblcurrency")
        self.frmStocks = QtWidgets.QFrame(self.centralwidget)
        self.frmStocks.setGeometry(QtCore.QRect(150, 110, 901, 501))
        self.frmStocks.setStyleSheet("background-color:rgb(0,0, 0);\n"
" border-top: 2px solid blue; \n"
" border-left: 2px solid blue; \n"
" border-right: 2px solid blue; \n"
" border-bottom: 2px solid blue; ")
        self.frmStocks.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmStocks.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmStocks.setObjectName("frmStocks")
        self.frame_6 = QtWidgets.QFrame(self.frmStocks)
        self.frame_6.setGeometry(QtCore.QRect(10, 10, 431, 281))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.lblStocks = QtWidgets.QLabel(self.frame_6)
        self.lblStocks.setGeometry(QtCore.QRect(10, 10, 131, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lblStocks.setFont(font)
        self.lblStocks.setStyleSheet("color: rgb(88, 150, 250);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lblStocks.setObjectName("lblStocks")
        self.lblstockname = QtWidgets.QLineEdit(self.frame_6)
        self.lblstockname.setGeometry(QtCore.QRect(150, 61, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblstockname.setFont(font)
        self.lblstockname.setStyleSheet("QLineEdit{\n"
"border: 2px solid rgb(37,39,48);\n"
"border-radius: 10px;\n"
"color: #FFF;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"background-color: rgb(34,36,44);\n"
"color:rgb(0,0,255);\n"
"}\n"
"QLineEdit:hover { border: 2px solid rgb(48,50,62);}QLineEdit:focus{border:2px solid rgb(48,50,60)n}")
        self.lblstockname.setAlignment(QtCore.Qt.AlignCenter)
        self.lblstockname.setObjectName("lblstockname")
        self.lblpricestocks = QtWidgets.QLabel(self.frame_6)
        self.lblpricestocks.setGeometry(QtCore.QRect(20, 100, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lblpricestocks.setFont(font)
        self.lblpricestocks.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lblpricestocks.setObjectName("lblpricestocks")
        self.lblsymbolstock = QtWidgets.QLabel(self.frame_6)
        self.lblsymbolstock.setGeometry(QtCore.QRect(20, 60, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lblsymbolstock.setFont(font)
        self.lblsymbolstock.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lblsymbolstock.setObjectName("lblsymbolstock")
        self.lblpricestocks_2 = QtWidgets.QLabel(self.frame_6)
        self.lblpricestocks_2.setGeometry(QtCore.QRect(160, 100, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lblpricestocks_2.setFont(font)
        self.lblpricestocks_2.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lblpricestocks_2.setText("")
        self.lblpricestocks_2.setObjectName("lblpricestocks_2")
        self.btnGetStock = QtWidgets.QPushButton(self.frame_6)
        self.btnGetStock.setGeometry(QtCore.QRect(330, 250, 91, 21))
        self.btnGetStock.setStyleSheet("QPushButton{\n"
"border: 2px solid rgb(37,39,48);\n"
"border-radius: 10px;\n"
"color: #FFF;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"background-color: rgb(34,36,44);\n"
"color:rgb(0,0,255);\n"
"}")
        self.btnGetStock.setObjectName("btnGetStock")
        self.lblmarketcap = QtWidgets.QLabel(self.frame_6)
        self.lblmarketcap.setGeometry(QtCore.QRect(20, 140, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lblmarketcap.setFont(font)
        self.lblmarketcap.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lblmarketcap.setObjectName("lblmarketcap")
        self.lblmarketcap_2 = QtWidgets.QLabel(self.frame_6)
        self.lblmarketcap_2.setGeometry(QtCore.QRect(160, 140, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lblmarketcap_2.setFont(font)
        self.lblmarketcap_2.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lblmarketcap_2.setText("")
        self.lblmarketcap_2.setObjectName("lblmarketcap_2")
        self.lblChanges = QtWidgets.QLabel(self.frame_6)
        self.lblChanges.setGeometry(QtCore.QRect(290, 100, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lblChanges.setFont(font)
        self.lblChanges.setStyleSheet("color: rgb(88, 1, 200);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lblChanges.setText("")
        self.lblChanges.setObjectName("lblChanges")
        self.framStocksLastSearched = QtWidgets.QFrame(self.frmStocks)
        self.framStocksLastSearched.setGeometry(QtCore.QRect(700, 10, 191, 481))
        self.framStocksLastSearched.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framStocksLastSearched.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framStocksLastSearched.setObjectName("framStocksLastSearched")
        self.lblStocks_2 = QtWidgets.QLabel(self.framStocksLastSearched)
        self.lblStocks_2.setGeometry(QtCore.QRect(10, 10, 91, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lblStocks_2.setFont(font)
        self.lblStocks_2.setStyleSheet("color: rgb(88, 150, 250);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.lblStocks_2.setObjectName("lblStocks_2")
        self.listgetstocks = QtWidgets.QListWidget(self.framStocksLastSearched)
        self.listgetstocks.setGeometry(QtCore.QRect(10, 50, 171, 421))
        self.listgetstocks.setStyleSheet("color: rgb(255, 255, 255);\n"
" border-top: 0px solid blue; \n"
" border-left: 0px solid blue; \n"
" border-right: 0px solid blue; \n"
" border-bottom: 0px solid blue; ")
        self.listgetstocks.setObjectName("listgetstocks")
        self.btnTicketDividents = QtWidgets.QPushButton(self.framStocksLastSearched)
        self.btnTicketDividents.setGeometry(QtCore.QRect(170, 10, 14, 14))
        self.btnTicketDividents.setMinimumSize(QtCore.QSize(14, 14))
        self.btnTicketDividents.setMaximumSize(QtCore.QSize(17, 17))
        self.btnTicketDividents.setToolTip("")
        self.btnTicketDividents.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 6px;        \n"
"    background-color: rgb(0, 150, 240);\n"
"}\n"
"QPushButton:hover {        \n"
"        background-color: rgb(0, 200, 255);\n"
"}")
        self.btnTicketDividents.setText("")
        self.btnTicketDividents.setIconSize(QtCore.QSize(14, 14))
        self.btnTicketDividents.setObjectName("btnTicketDividents")
        self.frmCompanyFormular.raise_()
        self.frmDashboard.raise_()
        self.frmFormular.raise_()
        self.frameup.raise_()
        self.frameleft.raise_()
        self.btn_minimize.raise_()
        self.btn_maximize.raise_()
        self.btn_close.raise_()
        self.frametop.raise_()
        self.framdown.raise_()
        self.frmStocks.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnDashboard.setText(_translate("MainWindow", "Dashboard "))
        self.btnFormular.setText(_translate("MainWindow", "Formular    "))
        self.btnStocks.setText(_translate("MainWindow", "Stocks         "))
        self.btnCompanyFormular.setText(_translate("MainWindow", "Company   "))
        self.btnForex.setText(_translate("MainWindow", "Forex          "))
        self.btnFutures.setText(_translate("MainWindow", "Futures       "))
        self.btnCrypto.setText(_translate("MainWindow", "Crypto       "))
        self.btnSettings.setText(_translate("MainWindow", "Settings     "))
        self.btnVersion.setText(_translate("MainWindow", "Version         "))
        self.lbldate.setText(_translate("MainWindow", "10-Sep-2020"))
        self.lblQuickOverview.setText(_translate("MainWindow", "Quick Overview"))
        self.label_2.setText(_translate("MainWindow", "Account 1"))
        self.label_4.setText(_translate("MainWindow", "Account 2"))
        self.label_6.setText(_translate("MainWindow", "Account 3"))
        self.label_7.setText(_translate("MainWindow", "Account 4"))
        self.lblQuickOverview_2.setText(_translate("MainWindow", "Stock Chart"))
        self.lblQuickOverview_3.setText(_translate("MainWindow", "Forex Chart"))
        self.lblQuickOverview_4.setText(_translate("MainWindow", "Futures Chart"))
        self.label_3.setText(_translate("MainWindow", "lblcompany"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Account_991050"))
        self.label_5.setText(_translate("MainWindow", "Amount:"))
        self.lineEdit.setText(_translate("MainWindow", "3000"))
        self.btnSend.setText(_translate("MainWindow", "Send"))
        self.btn_maximize.setToolTip(_translate("MainWindow", "Maximize"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.lblcapitalmanager.setText(_translate("MainWindow", "Capital Manager"))
        self.lblname.setText(_translate("MainWindow", "Dashboard"))
        self.btnSpend.setText(_translate("MainWindow", "Spend"))
        self.cbspendmoney.setCurrentText(_translate("MainWindow", "Main Account"))
        self.cbspendmoney.setItemText(0, _translate("MainWindow", "Main Account"))
        self.cbspendmoney.setItemText(1, _translate("MainWindow", "Account 1"))
        self.cbspendmoney.setItemText(2, _translate("MainWindow", "Account 2"))
        self.cbspendmoney.setItemText(3, _translate("MainWindow", "Account 3"))
        self.cbspendmoney.setItemText(4, _translate("MainWindow", "Account 4"))
        self.lespend.setText(_translate("MainWindow", "100"))
        self.lblSpendMoney.setText(_translate("MainWindow", "Spend Money"))
        self.lblSpendMoney_2.setText(_translate("MainWindow", "Spend Money"))
        self.pbSpendMoney.setFormat(_translate("MainWindow", "%p%"))
        self.pbSpendMoneyEuro.setFormat(_translate("MainWindow", "%p%"))
        self.lblHistory.setText(_translate("MainWindow", "History"))
        self.lblAccount2.setText(_translate("MainWindow", "Account 2"))
        self.lblAccount3.setText(_translate("MainWindow", "Account 3"))
        self.lblAccount1.setText(_translate("MainWindow", "Account 1"))
        self.lblTotal.setText(_translate("MainWindow", "Total"))
        self.lblMainAccount.setText(_translate("MainWindow", "Main Account"))
        self.lblAccount4.setText(_translate("MainWindow", "Account 4"))
        self.pbMainAccount.setFormat(_translate("MainWindow", "%p%"))
        self.btnSend_2.setText(_translate("MainWindow", "Get"))
        self.lblAccountStatistic.setText(_translate("MainWindow", "General Overview"))
        self.lblcurrency.setText(_translate("MainWindow", "%"))
        self.lblStocks.setText(_translate("MainWindow", "Stock Analysis"))
        self.lblstockname.setText(_translate("MainWindow", "TKA.DE"))
        self.lblpricestocks.setText(_translate("MainWindow", "Price:"))
        self.lblsymbolstock.setText(_translate("MainWindow", "Symbol:"))
        self.btnGetStock.setText(_translate("MainWindow", "Get"))
        self.lblmarketcap.setText(_translate("MainWindow", "Market Cap:"))
        self.lblStocks_2.setText(_translate("MainWindow", "Tickets"))
import main_rc
